name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements_flask.txt ]; then pip install -r requirements_flask.txt; fi
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Node deps
        run: |
          npm ci || npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Start backend server
        run: |
          nohup python3 run_backend.py &
          for i in {1..30}; do
            sleep 2
            curl -fsS http://localhost:5001/health && break || true
          done
      - name: Run backend API tests
        run: npm run test:api
      - name: Run E2E tests (headless)
        run: npm run test:e2e


