name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_flask.txt
        pip install -r requirements_test.txt
    
    - name: Run tests
      run: |
        python -m pytest backend/tests/ -v --tb=short
    
    - name: Run tests with coverage
      run: |
        python -m pytest backend/tests/ --cov=backend --cov-report=term-missing --cov-fail-under=60